image: node:latest

variables:
  NODE_ENV: production

cache:
  key:
    files:
      - package-lock.json
    prefix: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: pull-push

stages:
  - install-stage
  - validate-stage
  - test-stage
  - build-stage
  - deploy-stage

install_job:
  stage: install-stage
  script:
    - npm ci

lint_ts_job:
  stage: validate-stage
  script:
    - npm run lint:ts

test_job:
  stage: test-stage
  script:
    - npm run test:unit

lint_job:
  stage: test-stage
  script:
    - npm run lint:ts

build_job:
  stage: deploy-stage
  script:
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 week
