default:
  image: node:22-alpine
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
      - node_modules/
    policy: pull-push

stages:
  - install-stage
  - validate-stage
  - test-stage
  - build-stage

install_dependencies_job:
  stage: install-stage
  script:
    - npm ci --cache .npm --prefer-offline

lint_ts_job:
  stage: validate-stage
  script:
    - npm run lint:ts

lint_scss_job:
  stage: validate-stage
  script:
    - npm run lint:scss

test_job:
  stage: test-stage
  script:
    - npm run test:unit

build_job:
  stage: build-stage
  script:
    - npm run build:prod
